Move helm stuff into subdirectory
I was seeing this error:

```
Error: UPGRADE FAILED: create: failed to create: Secret "sh.helm.release.v1.prod.v49" is invalid: data: Too long: may not be more than 1048576 bytes
```

And it's because something wasn't covered by the helmignore and it was pulling in too much.